version: '3.7'
services:
    db:
        image: postgres
        container_name: nft_db
        environment:
            - POSTGRES_PORT=5432
            - POSTGRES_USER=nft
            - POSTGRES_PASSWORD=nft
            - POSTGRES_DB=nft
            
        ports:
            - '5432:5432'
        volumes:
            - ./db:/var/lib/postgresql/data"
        networks:
            - internal
    server:
        container_name: nft_server
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NFT_DB_HOST=db
        ports:
            - '8080:8080'
        depends_on: 
            - db
        networks:
            - internal
        stdin_open: true
volumes:
    db:  
    server:
networks:
    internal:
      driver: bridge
