// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Transaction struct {
	BlockNumber       *string `json:"blockNumber"`
	TimeStamp         *string `json:"timeStamp"`
	Hash              *string `json:"hash"`
	Nonce             *string `json:"nonce"`
	BlockHash         *string `json:"blockHash"`
	TransactionIndex  *string `json:"transactionIndex"`
	From              *string `json:"from"`
	To                *string `json:"to"`
	Value             *string `json:"value"`
	Gas               *string `json:"gas"`
	GasPrice          *string `json:"gasPrice"`
	IsError           *string `json:"isError"`
	TxreceiptStatus   *string `json:"txreceipt_status"`
	Input             *string `json:"input"`
	ContractAddress   *string `json:"contractAddress"`
	CumulativeGasUsed *string `json:"cumulativeGasUsed"`
	GasUsed           *string `json:"gasUsed"`
	Confirmations     *string `json:"confirmations"`
	MethodID          *string `json:"methodId"`
	FunctionName      *string `json:"functionName"`
}

type TrxErc1155 struct {
	BlockNumber       *string `json:"blockNumber"`
	TimeStamp         *string `json:"timeStamp"`
	Hash              *string `json:"hash"`
	Nonce             *string `json:"nonce"`
	BlockHash         *string `json:"blockHash"`
	TransactionIndex  *string `json:"transactionIndex"`
	Gas               *string `json:"gas"`
	GasPrice          *string `json:"gasPrice"`
	GasUsed           *string `json:"gasUsed"`
	CumulativeGasUsed *string `json:"cumulativeGasUsed"`
	Input             *string `json:"input"`
	ContractAddress   *string `json:"contractAddress"`
	From              *string `json:"from"`
	To                *string `json:"to"`
	TokenID           *string `json:"tokenID"`
	TokenValue        *string `json:"tokenValue"`
	TokenName         *string `json:"tokenName"`
	TokenSymbol       *string `json:"tokenSymbol"`
	Confirmations     *string `json:"confirmations"`
}

type TrxErc20 struct {
	BlockNumber       *string `json:"blockNumber"`
	TimeStamp         *string `json:"timeStamp"`
	Hash              *string `json:"hash"`
	Nonce             *string `json:"nonce"`
	BlockHash         *string `json:"blockHash"`
	From              *string `json:"from"`
	ContractAddress   *string `json:"contractAddress"`
	To                *string `json:"to"`
	Value             *string `json:"value"`
	TokenName         *string `json:"tokenName"`
	TokenSymbol       *string `json:"tokenSymbol"`
	TokenDecimal      *string `json:"tokenDecimal"`
	TransactionIndex  *string `json:"transactionIndex"`
	Gas               *string `json:"gas"`
	GasPrice          *string `json:"gasPrice"`
	GasUsed           *string `json:"gasUsed"`
	CumulativeGasUsed *string `json:"cumulativeGasUsed"`
	Input             *string `json:"input"`
	Confirmations     *string `json:"confirmations"`
}

type TrxErc721 struct {
	BlockNumber       *string `json:"blockNumber"`
	TimeStamp         *string `json:"timeStamp"`
	Hash              *string `json:"hash"`
	Nonce             *string `json:"nonce"`
	BlockHash         *string `json:"blockHash"`
	From              *string `json:"from"`
	ContractAddress   *string `json:"contractAddress"`
	To                *string `json:"to"`
	TokenID           *string `json:"tokenID"`
	TokenName         *string `json:"tokenName"`
	TokenSymbol       *string `json:"tokenSymbol"`
	TokenDecimal      *string `json:"tokenDecimal"`
	TransactionIndex  *string `json:"transactionIndex"`
	Gas               *string `json:"gas"`
	GasPrice          *string `json:"gasPrice"`
	GasUsed           *string `json:"gasUsed"`
	CumulativeGasUsed *string `json:"cumulativeGasUsed"`
	Input             *string `json:"input"`
	Confirmations     *string `json:"confirmations"`
}

type TrxInternal struct {
	BlockNumber     *string `json:"blockNumber"`
	TimeStamp       *string `json:"timeStamp"`
	Hash            *string `json:"hash"`
	From            *string `json:"from"`
	To              *string `json:"to"`
	Value           *string `json:"value"`
	ContractAddress *string `json:"contractAddress"`
	Input           *string `json:"input"`
	Type            *string `json:"type"`
	Gas             *string `json:"gas"`
	GasUsed         *string `json:"gasUsed"`
	TraceID         *string `json:"traceId"`
	IsError         *string `json:"isError"`
	ErrCode         *string `json:"errCode"`
}

type Event struct {
	CurrentBlock *string        `json:"currentBlock"`
	Transactions []*Transaction `json:"transactions"`
	TrxInternal  []*TrxInternal `json:"trxInternal"`
	TrxErc20     []*TrxErc20    `json:"trxERC20"`
	TrxErc721    []*TrxErc721   `json:"trxERC721"`
	TrxErc1155   []*TrxErc1155  `json:"trxERC1155"`
}
